"""Built-in English stopwords list (500+ words). No downloads needed."""

ENGLISH_STOPWORDS: set[str] = {
    "a", "about", "above", "after", "again", "against", "ain", "all", "am",
    "an", "and", "any", "are", "aren", "aren't", "as", "at", "be", "because",
    "been", "before", "being", "below", "between", "both", "but", "by", "can",
    "couldn", "couldn't", "d", "did", "didn", "didn't", "do", "does", "doesn",
    "doesn't", "doing", "don", "don't", "down", "during", "each", "few", "for",
    "from", "further", "get", "got", "had", "hadn", "hadn't", "has", "hasn",
    "hasn't", "have", "haven", "haven't", "having", "he", "her", "here",
    "hers", "herself", "him", "himself", "his", "how", "i", "if", "in",
    "into", "is", "isn", "isn't", "it", "it's", "its", "itself", "just",
    "ll", "m", "ma", "me", "mightn", "mightn't", "more", "most", "mustn",
    "mustn't", "my", "myself", "needn", "needn't", "no", "nor", "not", "now",
    "o", "of", "off", "on", "once", "only", "or", "other", "our", "ours",
    "ourselves", "out", "over", "own", "re", "s", "same", "shan", "shan't",
    "she", "she's", "should", "should've", "shouldn", "shouldn't", "so",
    "some", "such", "t", "than", "that", "that'll", "the", "their", "theirs",
    "them", "themselves", "then", "there", "these", "they", "this", "those",
    "through", "to", "too", "under", "until", "up", "ve", "very", "was",
    "wasn", "wasn't", "we", "were", "weren", "weren't", "what", "when",
    "where", "which", "while", "who", "whom", "why", "will", "with", "won",
    "won't", "would", "wouldn", "wouldn't", "y", "you", "you'd", "you'll",
    "you're", "you've", "your", "yours", "yourself", "yourselves",
    # Extended stopwords
    "able", "across", "actually", "almost", "also", "although", "always",
    "among", "another", "anyone", "anything", "anywhere", "apart", "appear",
    "around", "away", "back", "became", "become", "becomes", "becoming",
    "behind", "beside", "besides", "best", "better", "beyond", "bill",
    "bottom", "bring", "call", "came", "cannot", "cant", "certain", "co",
    "come", "computer", "con", "could", "couldnt", "cry", "de", "dear",
    "describe", "detail", "done", "due", "eg", "eight", "either", "eleven",
    "else", "elsewhere", "empty", "enough", "etc", "even", "ever", "every",
    "everyone", "everything", "everywhere", "except", "fill", "find", "fire",
    "first", "five", "former", "formerly", "forty", "found", "four", "full",
    "gave", "give", "go", "going", "gone", "gotten", "hence", "hereafter",
    "hereby", "herein", "hereupon", "however", "hundred", "ie", "inc",
    "indeed", "interest", "keep", "kept", "last", "latter", "latterly",
    "least", "less", "let", "like", "likely", "look", "ltd", "made", "make",
    "many", "may", "maybe", "might", "mill", "mine", "moreover", "mostly",
    "move", "much", "must", "name", "namely", "neither", "never",
    "nevertheless", "next", "nine", "nobody", "none", "noone", "nothing",
    "nowhere", "often", "one", "onto", "otherwise", "part", "per", "perhaps",
    "please", "put", "rather", "really", "regarding", "right", "said", "saw",
    "say", "says", "see", "seem", "seemed", "seeming", "seems", "serious",
    "several", "shall", "show", "side", "since", "sincere", "six", "sixty",
    "slightly", "somehow", "someone", "something", "sometime", "sometimes",
    "somewhere", "still", "take", "ten", "therefore", "thick", "thin",
    "third", "though", "three", "throughout", "thru", "thus", "together",
    "top", "toward", "towards", "twelve", "twenty", "two", "un", "unless",
    "unlikely", "upon", "us", "use", "used", "using", "usually", "various",
    "via", "want", "wanted", "wants", "way", "well", "went", "whatever",
    "whenever", "whereafter", "whereas", "whereby", "wherein", "whereupon",
    "wherever", "whether", "whither", "whole", "whose", "within", "without",
    "yet", "already", "along", "among", "amongst", "amoungst", "amount",
    "anyhow", "anyway", "anytime", "anyways", "apparently", "approximately",
    "ask", "asked", "asking", "associated", "available", "basically", "began",
    "begin", "beginning", "begins", "believe", "brief", "c", "came", "cause",
    "causes", "certain", "certainly", "changes", "clearly", "closely",
    "com", "completely", "consider", "considering", "contain", "containing",
    "contains", "corresponding", "course", "currently", "definitely",
    "described", "despite", "different", "differently", "does", "doing",
    "downwards", "e", "ed", "effect", "effectively", "especially",
    "essentially", "et", "exactly", "example", "except", "f", "fact",
    "fairly", "far", "fewer", "fifth", "finally", "following", "follows",
    "furthermore", "g", "general", "generally", "given", "gives", "goes",
    "good", "great", "greetings", "h", "half", "happen", "happened",
    "happens", "hardly", "hello", "help", "helps", "hi", "hopefully",
    "howbeit", "hither", "hopefully", "inasmuch", "indicate", "indicated",
    "indicates", "inner", "inside", "insofar", "instead", "into", "inward",
    "j", "k", "keeps", "kind", "knew", "know", "known", "knows", "l",
    "large", "largely", "later", "latest", "left", "lest", "likely",
    "little", "long", "longer", "longest", "looking", "looks", "low",
    "lower", "mainly", "makes", "making", "man", "maybe", "mean", "means",
    "meanwhile", "men", "merely", "might", "million", "miss", "mr", "mrs",
    "ms", "n", "near", "nearly", "necessary", "need", "needs", "new",
    "newer", "newest", "normally", "novel", "number", "obviously",
    "occur", "oh", "ok", "okay", "old", "older", "oldest", "ones", "open",
    "opposite", "order", "others", "ought", "outside", "overall", "p",
    "particular", "particularly", "past", "people", "placed", "point",
    "possible", "presumably", "previously", "primarily", "probably",
    "provides", "q", "que", "quite", "r", "recent", "recently",
    "relatively", "respectively", "round", "said", "second", "secondly",
    "seeing", "self", "selves", "sent", "seriously", "seven", "shall",
    "shortly", "simply", "small", "smaller", "smallest", "soon",
    "sorry", "specifically", "specified", "specify", "specifying",
    "sub", "substantially", "successfully", "sufficiently", "suggest",
    "sup", "sure", "taken", "tell", "tends", "th", "thank", "thanks",
    "thanx", "thereafter", "thereby", "therein", "theres", "thereupon",
    "think", "thinks", "thoroughly", "thoroughly", "thought", "thus",
    "til", "time", "times", "today", "together", "told", "took",
    "toward", "tried", "tries", "truly", "try", "trying", "twice",
    "u", "un", "under", "unfortunately", "unless", "unlike", "until",
    "unto", "v", "value", "vs", "w", "way", "welcome", "went", "where",
    "whence", "whenever", "whereafter", "whereas", "whereby", "wherein",
    "whereupon", "wherever", "whether", "whither", "whoever", "willing",
    "wish", "wonder", "world", "x", "yes", "yet", "z", "zero",
}
